{
  "language": "node_js",
  "os": [
    "linux"
  ],
  "dist": "xenial",
  "node_js": [
    "10.19.0"
  ],
  "cache": {
    "npm": true
  },
  "install": [
    "npm install"
  ],
  "script": [
    "npm test"
  ]
} 

# deploy:
#   - provider: s3
#     # rest of S3 deployment for MyApp.zip
#     # ⋮
#   - provider: codedeploy
#     access_key_id: "YOUR AWS ACCESS KEY"
#     secret_access_key: "YOUR AWS SECRET KEY"
#     bucket: "S3 Bucket"
#     key: latest/MyApp.zip
#     application: MyApp
#     deployment_group: MyDeploymentGroup